window.PROJECTS = [
      {
        id: 1,
        title: "Terolles",
        folder: "Terolles",
        year: "2025",
        description: "3D survival game focused on Rust-like resource collection and building.",
        longDescription:
          "Terolles is a 3D survival game focused on Rust-style resource collection and building. It integrates several game systems from a survival genre together: inventory and hotbar, resource collection (including trees and rocks that fracture), socket-based building, health and sprint mechanics, food that restores health and stamina.",
        context: "CSC 498 (Independent Study in Computer Science)",
        engine: "Unreal Engine",
        scope: "10 Weeks",
        team: "Solo",
        roles: ["Programming", "System Design"],
        skills: ["Blueprint visual scripting", "Widgets", "Foliage", "Mesh Fracturing", "Sockets", "C++", "System Design"],
        features: ["Player inventory & hotbar", "Socket-based building system", "Resource gathering", "Health, stamina & food"],
        category: "Game Dev",
        featured: true,
        links: { video: "https://www.youtube.com/watch?v=QUZoxKvWkEI" }
      },
      {
        id: 2,
        title: "The Deep End",
        folder: "The Deep End",
        year: "2026",
        description:
          "3D game about diving deep below a pool to collect pool toys.",
        longDescription:
          "A 3D game about diving deep below a pool to collect pool toys, making friends and fighting eldrich abominations along the way.",
        context: "2026 Triangle Game Jam",
        engine: "Godot",
        scope: "1 Week",
        team: "Group (5)",
        roles: ["Gameplay Programming", "System Design"],
        skills: ["User Interface Design", "Gameplay Programming", "Level Design", "Economy/Shop/Item Design", "Music & Sound Design", "Gameplay Optimization"],
        features: ["Underwater movement", "Breath & health systems", "In-game shop"],
        caseStudy: {
            tagline: "A more in-depth list of features I implemented and what design principles I followed.",
            designPillars: [
                { title: "Flow-first gameplay", detail: "Avoid menus that interrupt play, keep decisions in-world for fast, responsive gameplay. Ensure strong feedback and renforce player input." },
                { title: "Depth feels different", detail: "Underwater movement and visuals should feel heavier, slower, and immersive. Audio should match, heightening player emotions." },
                { title: "Balanced but meaningful player decisions", detail: "Player decisions should matter, shop items should impact gameplay and be a core driver of the gameplay loop." },
            ],
            contributions: [
                {
                title: "Land + underwater movement",
                bullets: [
                    "Built dual-mode movement: slower velocity & higher momentum underwater to sell weight and inertia.",
                    "Applied an underwater shader with subtle player bobbing to reinforce the 'submerged' feeling.",
                    "Included an underwater sprint mechanic to allow for enemy kiting for further skill expression.",
                ],
                },
                {
                title: "Shop system",
                bullets: [
                    "Implemented a shop system, not using a flow-stopping shop UI, instead opting to provide the player with a semi-random selection of 3 items",
                    "Hooked up each item to real gameplay effects: stats changes, audio, icons, headlamp light, weapon swaps.",
                    "Balanced prices to encourage variety while keeping player decisions relevant. Items have early accessibility with a scaling cost for stronger upgrades.",
                ],
                },
                {
                title: "Breath & health systems",
                bullets: [
                    "Dynamic breath drain based on depth, underwater sprint drains even faster.",
                    "Health refills after a delay to promote continued dives instead of 'death-reset' player behavior.",
                    "Implemented death to respawn at poolside for a quick loop reset and to keep flow uninterrupted.",
                ],
                },
                {
                title: "World & collaboration",
                bullets: [
                    "Greyboxed levels and iterated with 3D artists to keep the space playable, readable and exciting.",
                ],
                },
                {
                title: "UX, audio, settings",
                bullets: [
                    "Designed sampled SFX for strong action feedback and immersion.",
                    "Built hover-based interaction prompts for interactable items: NPCs, coins, shop items (including cost display), toys, thrown items, etc.",
                    "Implemented pause and options menus allowing players to adjust keybinds, audio levels, fullscreen, vsync, shadow quality.",
                ],
                },
                {
                title: "Performance improvements",
                bullets: [
                    "Used the Godot profiler to locate and fix performance issues after jam submission.",
                ],
                },
            ]
            },
        category: "Game Dev",
        featured: true,
        links: { itch: "https://memjamim.itch.io/the-deep-end", video: "https://www.youtube.com/watch?v=Cf8b2OEy0L4" }
      },
      {
        id: 3,
        title: "Sporadic",
        folder: "Sporadic",
        year: "2025",
        description: "2D platformer with randomized abilities similar to Mosa Lina.",
        longDescription:
          "A 2D platformer where the player is assigned 3 semi-random movement abilities used to evade enemies and reach the goal. All abilities have more powerful variants that while the player is in 'Chaos Mode'.",
        context: "CSC 281 (Foundations of Interactive Game Design)",
        engine: "Unity",
        scope: "5 Weeks",
        team: "Group (4)",
        roles: ["Level Design", "Programming"],
        skills: ["C#", "GitHub", "Game Balance", "Agile Development"],
        features: ["Ability randomization", "Chaos coins", "Several platforming levels", "Key & door level progression", "Moving enemies", "Level select", "Pixel art"],
        category: "Game Dev",
        featured: false,
        links: { video: "https://www.youtube.com/watch?v=LMVzqrG87_Y" }
      },
      {
        id: 4,
        title: "Lizard101 (Physical)",
        folder: "Lizard101 (Physical)",
        year: "2023",
        description: "Physical PvE card game with combat inspired by Wizard101.",
        longDescription:
          "Up to 3 players of different elemental types (Fire, Water, Plant) use their cards to defeat rounds of enemies, upgrading their deck and gear along the way.",
        context: "VGDC Spring Game Jam",
        engine: "Physical Board Game",
        scope: "2 Weeks",
        team: "Group (3)",
        roles: ["Production", "Card Design", "Usability Testing"],
        skills: ["Card Design", "Game Balance", "Project Management", "Graphic Design"],
        features: ["100+ cards", "6 playable characters", "PvE scaling", "Deckbuilding progression system"],
        category: "Game Dev",
        featured: false,
        links: {}
      },
      {
        id: 5,
        title: "The Janitor",
        folder: "The Janitor",
        year: "2022",
        description: "2D arcade-style game about defending a mall from aliens.",
        longDescription:
          "Enemies spawn in bathrooms which you must repair while using your mop to fend off endless hoards of incoming alien invaders.",
        context: "VGDC Fall Game Jam",
        engine: "Unity",
        scope: "2 Weeks",
        team: "Group (5)",
        roles: ["Level Design", "2D Art"],
        skills: ["2D Level Design", "Pixel Art", "CAD", "Discord", "Trello"],
        features: ["Repair mechanics", "Wave-based combat", "Mall environment"],
        category: "Game Dev",
        featured: false,
        links: { itch: "https://imperite.itch.io/the-janitor" }
      },
      {
        id: 6,
        title: "Elemental Dungeon Escape",
        folder: "EDE",
        year: "2025",
        description: "2D elemental block-pushing puzzle game.",
        longDescription:
          "A block-pushing puzzle game where elemental blocks create specific effects: trees grow, acid melts walls, rock creates new ones, fire spreads, water blocks fire, and goblin poison kills goblins of course! Did I forget to mention that there are goblins that chase the player?",
        context: "CSC 281 (Foundations of Interactive Game Design)",
        engine: "PuzzleScript",
        scope: "1 Week",
        team: "Solo",
        roles: ["Puzzle Design", "Programming", "Pixel Art"],
        skills: ["Puzzle Design", "Pixel Art", "Level Design"],
        features: ["Interactive mechanics", "Element-based effects", "Enemy movement", "Level design"],
        category: "Game Dev",
        featured: false,
        links: { video: "https://www.youtube.com/watch?v=UTHJ_Aleee0" }
      },
      {
        id: 7,
        title: "A Game About Climbing A Tower",
        folder: "Tower",
        year: "2025",
        description: "Text-based story game about a guy climbing a tower.",
        longDescription:
          "A text-based narrative experience that tells the story of a man climbing a radio tower.",
        context: "CSC 281 (Foundations of Interactive Game Design)",
        engine: "Twine",
        scope: "1 Week",
        team: "Solo",
        roles: ["Narrative Design"],
        skills: ["Story Design", "Storyboarding", "Narrative Progression", "CSS"],
        features: ["Branching interactive narrative"],
        category: "Game Dev",
        featured: false,
        links: {}
      },
      {
        id: 8,
        title: "Duck Escape",
        folder: "Duck Escape",
        year: "2025",
        description: "Award-winning 2.5D 'Getting Over It' style platformer.",
        longDescription:
          "Escape a lab using your freakishly long beak to climb, bounce, and dig to escape when an earthquake weakens the lab's foundations. This game placed 3rd and won 'Best Character' at the NC State Collegiate Game Jam out of 15 teams.",
        context: "NC State Collegiate Game Jam",
        engine: "Unity",
        scope: "3 Days",
        team: "Group (4)",
        roles: ["Gameplay Programming", "Level Design", "Sound Design"],
        skills: ["Unity Physics", "Gameplay Design", "Level Design", "Music & Sound Design"],
        features: ["Physics-based movement", "Item holding, dropping & door opening", "Three platforming levels", "Custom music and sounds"],
        category: "Game Dev",
        featured: true,
        links: { itch: "https://kwm1tsu.itch.io/duck-escape", video: "https://www.youtube.com/watch?v=StcqCY1djnc" }
      },
      {
        id: 9,
        title: "Lizard101 (Digital)",
        folder: "Lizard101 (Digital)",
        year: "2025",
        description: "2D deckbuilding roguelike built on a custom C++ game engine.",
        longDescription:
          "A digital adaptation of the card game designed as a demonstration of engine features. Features different elemental types (Fire, Water, Plant) with unique cards, several rounds of enemies, deckbuilding between rounds, and 1, 2 and 3 player modes",
        context: "CSC 481 (Game Engine Foundations)",
        engine: "Custom Game Engine",
        scope: "3 Weeks",
        team: "Group (3)",
        roles: ["Gameplay Programming", "System Design", "Card Design"],
        skills: ["C++", "System Architecture", "Pitched Concept", "Card Balance & Design", "Game Design"],
        features: ["Multiplayer combat", "Elemental card archetypes", "Aura and trap cards", "3 unique playable characters", "Deckbuilding progression system"],
        category: "Game Dev",
        featured: true,
        links: { video: "https://www.youtube.com/watch?v=wWISnXFZp_8" }
      },
      {
        id: 10,
        title: "Wolf Cafe",
        folder: "Wolfcafe",
        year: "2024",
        description: "Full-stack GrubHub-style system for ordering and inventory.",
        longDescription:
          "A comprehensive ordering system where customers order recipes fulfilled by staff. Staff can manage ingredients, inventory, recipes, orders, and user roles. Includes a layered architecture and extensive unit & system testing.",
        context: "CSC 326 (Software Engineering)",
        engine: "Java/Spring/React",
        scope: "15 Weeks",
        team: "Group (6)",
        roles: ["Full Stack Development"],
        skills: ["MySQL", "Hibernate", "REST", "JUnit", "GitHub Actions", "Java"],
        features: ["Unit & integration testing", "Layered architecture", "Requirements design", "Extensive documentation"],
        category: "Software",
        featured: true,
        links: { github: "https://github.com/ncstate-csc-coursework/csc326-2025-fall-tp-213-1" }
      },
      {
        id: 11,
        title: "Custom Game Engine",
        folder: "Custom Game Engine",
        year: "2025",
        description: "Custom 2D game engine built with C++ using SDL 3 for rendering.",
        longDescription:
          "Custom 2D game engine made from the ground up, complete with a component-based game object model, client-server networking architecture, event management system, multithreading, and custom memory management. Made in C++ using SDL 3 and SDL 3 Image for rendering. Two demo games were created to demonstrate engine features: Lizard101, a deckbuilding card game, and Journey to nyx, a simple 2D platformer.",
        context: "CSC 481 (Game Engine Foundations)",
        engine: "C++ / SDL 3",
        scope: "15 Weeks",
        team: "Group (3)",
        roles: ["Backend Development"],
        skills: ["SDL 3", "CMake", "C++", "ZeroMQ/CPPZMQ", "Multithreading", "Memory Management"],
        features: ["Client-server networking", "Component-based objects", "Event & time management", "Queuing & synchronization"],
        category: "Software",
        featured: true,
        links: { github: "#" }
      },
      {
        id: 12,
        title: "Trees For The Triangle App Design",
        folder: "Trees For The Triangle App Design",
        year: "2025",
        description: "Frontend designs in Figma for a sponsor's project management system.",
        longDescription:
          "Worked with sponsor Trees for the Triangle to create frontend designs in Figma for their project management system. Produced wireframes and interactive prototypes, ran usability testing, and iterated designs based on sponsor feedback and presentations.",
        context: "CSC 454 (Human Computer Interaction)",
        engine: "Figma / HTML / CSS",
        scope: "12 Weeks",
        team: "Group (4)",
        roles: ["Frontend Design"],
        skills: ["Wireframing", "Usability Testing", "Prototyping", "Sponsor Collaboration", "Figma", "HTML", "CSS"],
        features: ["Aesthetically pleasing app design", "Straightfoward interactive prototypes", "Usability testing reports", "Design iterations"],
        category: "Software",
        featured: false,
        links: {}
      },
    ];